//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDBLyricsSearcherPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTDBLyricsSearcherPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Name&quot;: &quot;うたまっぷ&quot;,
        ///    &quot;Encoding&quot;: &quot;shift_jis&quot;,
        ///    &quot;Url&quot;: &quot;https://www.utamap.com&quot;,
        ///    &quot;ParamFormat&quot;: &quot;/searchkasi.php?searchname=title&amp;word={title}&amp;act=search&amp;search_by_keyword=%8C%9F%26%23160%3B%26%23160%3B%26%23160%3B%8D%F5&amp;sortname=1&amp;pattern=4&quot;,
        ///    &quot;ListBlockRegex&quot;: &quot;&lt;th class=ct bgcolor=#f3ffe6&gt;タイアップ情報&lt;/th&gt;\\s*&lt;/tr&gt;(.+?)\\s*&lt;/table&gt;&quot;,
        ///    &quot;ListItemRegex&quot;: &quot;&lt;tr bgColor=#ffffff&gt;(.+?)&lt;/tr&gt;&quot;,
        ///    &quot;ItemUrlRegex&quot;: &quot;&lt;A href=\&quot;(.+?)\&quot;&gt;&quot;,
        ///    &quot;ItemTitleRegex&quot;: &quot;&lt;A href=\&quot;[^\&quot;]+\&quot;&gt;(.+)&lt;/a&gt;&quot;,        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlLyricsSiteList {
            get {
                return ResourceManager.GetString("HtmlLyricsSiteList", resourceCulture);
            }
        }
    }
}
